- hosts: all
  name: Set up instances
  user: vagrant
  gather_facts: True
  vars:
    provisioner: virtualbox
    distribution: centos
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  tasks:
    - name: ensure all interfaces are up
      become: True
      service: name=network enabled=yes state=restarted
  roles:
    - base

- hosts: dhcpmaster
  become: true
  vars:
    dhcp_global_authoritative: authoritative
    dhcp_global_log_facility: local7
    dhcp_global_bootp: allow
    dhcp_global_booting: allow
    dhcp_global_next_server: 172.28.128.15
    dhcp_global_filename: boot.img
    dhcp_global_default_lease_time: 28800 # 8hrs
    dhcp_global_max_lease_time: 43200 # 12 hrs
    dhcp_global_subnet_mask: 255.255.255.0
    dhcp_global_broadcast_address: 172.28.128.255
    dhcp_global_routers: 10.0.2.2
    dhcp_global_domain_name: educacionit.com
    dhcp_global_domain_name_servers:
      - 172.28.128.11
      - 172.28.128.12
    dhcp_subnets:
      - ip: 172.28.128.0
        netmask: 255.255.255.0
        default_lease_time: 1800
        max_lease_time: 3600
        dhcp_domain: educacionit.com
        dhcp_broadcast_address: 172.28.128.255
        dhcp_netbios_address: 172.28.128.100
        domain_name_servers:
          - 172.28.128.11
          - 172.28.128.12
        routers: 10.0.2.2
        range_begin: 172.28.128.140
        range_end: 172.28.128.150
        server_name: dhcp
        netbios_mode_type: 8
        www_server: 172.28.128.20
        pop_server: 172.28.128.22
        smtp-server:  172.28.128.21
        ip_forwarding : off
        option_subnet_mask: 255.255.255.0
        option_dhcp_message_type: 5
        option_dhcp_server_identifier: 10.0.2.2

    dhcp_hosts:
      - name: ipxemaster
        mac: '08:00:27:83:a7:15'
        ip: 172.28.128.15
  roles:
    - ansible_role_dhcp
