---
- hosts: all
  name: Set up instances
  user: vagrant
  gather_facts: True
  vars:
    provisioner: virtualbox
    distribution: centos
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  roles:
    - base


- hosts: machine1
  name: Set up Dns Server
  user: vagrant
  gather_facts: True
  vars:
    provisioner: virtualbox
    distribution: centos
    dns_enabled: True
    dns_chroot_enabled: False
    recursion: yes
    zone_names:
      - educacionit.com.
    #  - laboratorio.com.
    forward_zones_reg: False
    #forward_zones:
    #  - { zone: "educaciontit.com.", forwarders: "10.4.2.210; 10.4.8.3;" }
    zone_address: 184.73.229.52
    allow_query_from: "any; "
    allow_recursion_from: "10.0.0.0/8; 172.16.0.0/12; 192.168.0.0/16;"
    name_servers:
      - public-ns1.educacionit.com.
      - public-ns2.educacionit.com.
    mail_servers:
      - " 10 smtp.educacionit.com."
    #laboratorio_com_public_servers:
    #  - { hostname: public-ns1, ip: 184.73.229.52 }
    #  - { hostname: public-ns2, ip: 184.73.229.52 }
    #  - { hostname: ca, ip: 184.73.229.52 }
    #  - { hostname: smtp, ip: 184.73.229.52 }
    educacionit_com_public_servers:
      - { hostname: public-ns1, ip: 192.168.1.1 }
      - { hostname: public-ns2, ip: 192.168.1.2 }
      - { hostname: smtp, ip: 192.168.1.1 }
      - { hostname: wiki, ip: 192.168.1.1 }
    dns_server_list: "{{educacionit_com_public_servers}}"
      # "{{educacionit_com_public_servers}},{{laboratorio_com_public_servers}}"
      #- "{{educacionit_com_public_servers}}"
      #- "{{laboratorio_com_public_servers}}"
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  roles:
    - dns

- hosts: machine2
  name: Set up Dns Server
  user: vagrant
  gather_facts: False
  vars:
    provisioner: virtualbox
    distribution: centos
    dns_enabled: True
    dns_chroot_enabled: False
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  roles:
    - dns
