---

- hosts: all
  name: Set up instances
  user: vagrant
  gather_facts: True
  vars:
    provisioner: virtualbox
    distribution: centos
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  roles:
    - base

- hosts: testbindmaster
  become: true
  vars:
    bind_zone_master_server_ip_status: True
    bind_zone_slave_server_ip_status: False
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_listen_ipv6:
      - any
    bind_acls:
      - name: acl1
        match_list:
          - 172.28.128.0/24
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: true
    bind_zone_networks:
      - '172.28.128'
      - '10'
    bind_zone_ipv6_networks:
      - '2001:db8:0:1::/64'
    bind_zone_name: 'educacionit.com'
    bind_zone_master_server_ip: 172.28.128.11
    bind_zone_name_servers:
      - ns1
      - ns2
    bind_zone_hosts:
      - name: ns1
        ip: 172.28.128.11
        ipv6: 2001::db8:0:1:119
      - name: ns2
        ip: 172.28.128.12
        ipv6: 2001::db8:0:1:118
      - name: srv001
        ip: 172.28.128.20
        ipv6: 2001::db8:0:1:20
        aliases:
          - wwww
      - name: srv002
        ip: 172.28.128.19
        ipv6: 2001::db8:0:1:19
        aliases:
          - mysql
      - name: mail001
        ip: 172.28.128.21
        ipv6: 2001::db8:0:1:21
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 172.28.128.22
        ipv6: 2001::db8:0:1:22
        aliases:
          - pop
          - mail-out
      - name: webmail
        ip: 172.28.128.23
      - name: dhcp
        ip: 172.28.128.100
      - name: proxy
        ip: 172.28.128.25
    bind_zone_mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    bind_zone_services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: proxy
    bind_zone_text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
  tasks:
    - name: ensure all interfaces are up
      become: True
      service: name=network enabled=yes state=restarted
    - name: Configuring ipv6
      become: True
      command: ip -6 addr add 2001::db8:0:1:119/64 dev enp0s8
  roles:
    - ansible_role_dns

- hosts: testbindslave
  become: true
  vars:
    bind_zone_master_server_ip_status: False
    bind_zone_slave_server_ip_status: True
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_listen_ipv6:
      - any
    bind_acls:
      - name: acl1
        match_list:
          - 172.28.128.0/24
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: true
    bind_zone_networks:
      - '172.28.128'
      - '10'
    bind_zone_ipv6_networks:
      - '2001:db8:0:1::/64'
    bind_zone_name: 'educacionit.com'
    bind_zone_master_server_ip: 172.28.128.11
    bind_zone_name_servers:
      - ns1
      - ns2
    bind_zone_hosts:
      - name: ns1
        ip: 172.28.128.11
        ipv6: 2001::db8:0:1:119
      - name: ns2
        ip: 172.28.128.12
        ipv6: 2001::db8:0:1:118
      - name: srv001
        ip: 172.28.128.20
        ipv6: 2001::db8:0:1:20
        aliases:
          - wwww
      - name: srv002
        ip: 172.28.128.19
        ipv6: 2001::db8:0:1:19
        aliases:
          - mysql
      - name: mail001
        ip: 172.28.128.21
        ipv6: 2001::db8:0:1:21
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 172.28.128.22
        ipv6: 2001::db8:0:1:22
        aliases:
          - pop
          - mail-out
      - name: webmail
        ip: 172.28.128.23
      - name: dhcp
        ip: 172.28.128.100
      - name: proxy
        ip: 172.28.128.25
    bind_zone_mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    bind_zone_services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: proxy
    bind_zone_text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
  tasks:
    - name: ensure all interfaces are up
      become: True
      service: name=network enabled=yes state=restarted
    - name: Configuring ipv6
      become: True
      command: ip -6 addr add 2001::db8:0:1:118/64 dev enp0s8
  roles:
    - ansible_role_dns
