---

- hosts: all
  name: Set up instances
  user: vagrant
  gather_facts: True
  vars:
    provisioner: virtualbox
    distribution: centos
  vars_files:
    - "vars_files/{{distribution}}-{{provisioner}}-vars.yml"
    - "vars_files/{{distribution}}.yml"
  roles:
    - base

- hosts: testbindmaster
  become: true
  vars:
    bind_zone_master_server_ip_status: True
    bind_zone_slave_server_ip_status: False
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_listen_ipv6:
      - any
    bind_acls:
      - name: acl1
        match_list:
          - 172.28.128.0/24
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: true
    bind_zone_networks:
      - '172.28.128'
      - '10'
    bind_zone_ipv6_networks:
      - '2001:db8::/48'
    bind_zone_name: 'educacionit.com'
    bind_zone_master_server_ip: 172.28.128.11
    bind_zone_name_servers:
      - ns1
      - ns2
    bind_zone_hosts:
      - name: ns1
        ip: 172.28.128.11
      - name: ns2
        ip: 172.28.128.12
      - name: srv001
        ip: 172.28.128.11
        ipv6: 2001:db8::1
        aliases:
          - www
      - name: srv002
        ip: 172.28.128.12
        ipv6: 2001:db8::2
        aliases:
          - mysql
      - name: mail001
        ip: 172.28.128.11
        ipv6: 2001:db8::d:1
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 172.28.128.11
        ipv6: 2001:db8::d:2
      - name: mail003
        ip: 172.28.128.12
        ipv6: 2001:db8::d:3
        aliases:
          - imap
          - mail-out
      - name: srv010
        ip: 172.28.128.11
      - name: srv011
        ip: 172.28.128.12
      - name: srv012
        ip: 172.28.128.11
    bind_zone_mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    bind_zone_services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: srv010
    bind_zone_text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
  tasks:
    - name: ensure all interfaces are up
      become: True
      service: name=network enabled=yes state=restarted
  roles:
    - ansible_role_dns

- hosts: testbindslave
  become: true
  vars:
    bind_zone_master_server_ip_status: False
    bind_zone_slave_server_ip_status: True
    bind_allow_query:
      - any
    bind_listen_ipv4:
      - any
    bind_listen_ipv6:
      - any
    bind_acls:
      - name: acl1
        match_list:
          - 172.28.128.0/24
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_recursion: true
    bind_zone_networks:
      - '172.28.128'
      - '10'
    bind_zone_ipv6_networks:
      - '2001:db8::/48'
    bind_zone_name: 'educacionit.com'
    bind_zone_master_server_ip: 172.28.128.11
    bind_zone_name_servers:
      - ns1
      - ns2
    bind_zone_hosts:
      - name: ns1
        ip: 172.28.128.11
      - name: ns2
        ip: 172.28.128.12
      - name: srv001
        ip: 172.28.128.11
        ipv6: 2001:db8::1
        aliases:
          - www
      - name: srv002
        ip: 172.28.128.12
        ipv6: 2001:db8::2
        aliases:
          - mysql
      - name: mail001
        ip: 172.28.128.11
        ipv6: 2001:db8::d:1
        aliases:
          - smtp
          - mail-in
      - name: mail002
        ip: 172.28.128.11
        ipv6: 2001:db8::d:2
      - name: mail003
        ip: 172.28.128.12
        ipv6: 2001:db8::d:3
        aliases:
          - imap
          - mail-out
      - name: srv010
        ip: 172.28.128.11
      - name: srv011
        ip: 172.28.128.12
      - name: srv012
        ip: 172.28.128.11
    bind_zone_mail_servers:
      - name: mail001
        preference: 10
      - name: mail002
        preference: 20
    bind_zone_services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: srv010
    bind_zone_text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
  tasks:
    - name: ensure all interfaces are up
      become: True
      service: name=network enabled=yes state=restarted
  roles:
    - ansible_role_dns
