require 'rbconfig'
Vagrant.configure("2") do |config2|
  X = 1

  VAGRANT_VM_PROVIDER = "virtualbox"
  ANSIBLE_RAW_SSH_ARGS = []

  (1..X-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS < "-o IdentityFile=.vagrant/machines/hostA#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..X).each do |machine_id|
    config2.vm.define "hostA#{machine_id}" do |machine2|
      #config.vm.network "public_network", bridge: "en0", use_dhcp_assigned_default_route: true
      machine2.vm.box = "debian/stretch64"
      machine2.vm.hostname = "hostA#{machine_id}"
      machine2.vm.network "private_network", ip: "10.1.1.15", auto_config: false

      # manual ip private eth1
      config2.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip private eth1 10.1.1.15';ip address flush dev eth1;ip address add 10.1.1.15/16 dev eth1; ip link set dev eth1 up"

      #forwarding
      config2.vm.provision "shell",
      run: "always",
      inline: "echo 'enableing ip forwarding';echo 1 > /proc/sys/net/ipv4/ip_forward"

      #install net-tools
      config2.vm.provision "shell",
      run: "always",
      inline: "apt-get install net-tools --assume-yes"

      # delete default gw on eth0
      config2.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"

      # default router
      config2.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for bridge interface';ip route add default via 10.1.1.2"
      #inline: "ip route add default via 192.168.2.1 dev eth1"



    end
  end
end


