- include: "roles/ftp/tasks/base-{{package_manager}}-ftp.yml"

- include: "roles/ftp/tasks/configure.yml"
  when: vsftpd_enabled == True


- name: Copy lftp config for ssl use
  become: True
  template:
    src: ".lftprc.j2"
    dest: "/root/.lftprc"
    owner: root
    group: root
    mode: 0600


- name: Copy lftp config for ssl use
  become: True
  template:
    src: "runssl.sh"
    dest: "/root/runssl.sh"
    owner: root
    group: root
    mode: 0700
