# vi: set ft=ruby

require 'rbconfig'

ROLE_NAME = 'bind'
BASE_NAME = 'test' + ROLE_NAME
hosts = [
{ name: 'master' , ip: '172.28.128.11', ipv6: '2001::db8:0:1:119/64', mac: '080027beb5c6' },
{ name: 'slave' , ip: '172.28.128.12', ipv6: '2001::db8:0:1:118/64',  mac: '08002783a7aa' }
]
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'bertvv/centos72'

  hosts.each do |host|
    host_name = BASE_NAME + host[:name]

    config.vm.define host_name do |node|
      node.vm.hostname = host_name
      #node.vm.network 'private_network', type: "dhcp"
      node.vm.network 'private_network', type: "dhcp", :mac => host[:mac]
    #  node.vm.network 'private_network', ip: host[:ip], ipv6: host[:ipv6], :mac => host[:mac]
      #node.vm.provision "shell",
      #run: "always",
      #inline: "ip -6 addr add host[:ipv6] dev eth1 "
      node.vm.provision 'ansible' do |ansible|
        ansible.playbook = "../../../../playbook/dnsmaster.yml"
      end
    end
  end
end
