# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/26-cloud-base"

#config.vm.network "private_network", ip: "127.0.0.1"
config.vm.network "public_network",ip: "192.168.2.155", :bridge => 'en0: Wi-Fi (AirPort)'
config.vm.network "public_network",type: "dhcp", :bridge => 'en0: Wi-Fi (AirPort)'
config.vm.synced_folder '.', '/vagrant', disabled: true
end
