# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/6"
  config.vm.network 'public_network', ip: "192.168.1.155"
  # config.vm.network "private_network", type: "dhcp", virtualbox__natnets: "edit"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

#Jun 12 04:01:01 localhost ntpdate[7662]: the NTP socket is in use, exiting
#Jun 12 04:03:21 localhost dhclient[5926]: DHCPREQUEST on eth0 to 10.10.0.1 port 67 (xid=0x9adff91)
#Jun 12 04:03:21 localhost dhclient[5926]: DHCPACK from 10.10.0.1 (xid=0x9adff91)
#Jun 12 04:03:23 localhost dhclient[5926]: bound to 10.10.10.1 -- renewal in 469 seconds.
#Jun 12 04:03:29 localhost dhcpd: DHCPREQUEST for 192.168.1.27 from 08:00:27:a0:86:bb via eth2: unknown lease 192.168.1.27.
#Jun 12 04:03:29 localhost dhcpd: DHCPREQUEST for 192.168.1.27 from 08:00:27:a0:86:bb via eth1: unknown lease 192.168.1.27.
#Jun 12 04:03:29 localhost dhcpd: DHCPDISCOVER from 08:00:27:a0:86:bb via eth2
#Jun 12 04:03:30 localhost dhcpd: DHCPOFFER on 192.168.1.30 to 08:00:27:a0:86:bb (www.systeminteg.com) via eth2
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#45099: signer "rndc-key" approved
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#45099: updating zone 'systeminteg.com/IN': adding an RR at 'www.systeminteg.com.systeminteg.com' A
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#45099: updating zone 'systeminteg.com/IN': adding an RR at 'www.systeminteg.com.systeminteg.com' TXT
#Jun 12 04:03:30 localhost dhcpd: Added new forward map from www.systeminteg.com.systeminteg.com to 192.168.1.30
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#42039: signer "rndc-key" approved
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#42039: updating zone '1.168.192.in-addr.arpa/IN': deleting rrset at '30.1.168.192.in-addr.arpa' PTR
#Jun 12 04:03:30 localhost named[7529]: client 127.0.0.1#42039: updating zone '1.168.192.in-addr.arpa/IN': adding an RR at '30.1.168.192.in-addr.arpa' PTR
#Jun 12 04:03:30 localhost dhcpd: added reverse map from 30.1.168.192.in-addr.arpa. to www.systeminteg.com.systeminteg.com
#Jun 12 04:03:30 localhost dhcpd: DHCPREQUEST for 192.168.1.30 (192.168.1.133) from 08:00:27:a0:86:bb (www.systeminteg.com) via eth2
#Jun 12 04:03:30 localhost dhcpd: DHCPACK on 192.168.1.30 to 08:00:27:a0:86:bb (www.systeminteg.com) via eth2
#un 12 04:03:30 localhost dhcpd: DHCPREQUEST for 192.168.1.30 (192.168.1.133) from 08:00:27:a0:86:bb (www.systeminteg.com) via eth1
#Jun 12 04:03:30 localhost dhcpd: DHCPACK on 192.168.1.30 to 08:00:27:a0:86:bb (www.systeminteg.com) via eth1
#Jun 12 04:06:22 localhost ntpd[1582]: 0.0.0.0 0617 07 panic_stop +30835 s; set clock manually within 1000 s.
