# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# vi: set ft=ruby

require 'rbconfig'

ROLE_NAME = 'master'
BASE_NAME = 'dhcp'
#BASE_NAME = 'test' + ROLE_NAME
#v4prefix = "172.28.128."
#v6prefix = "fddd::"
hosts = [
{ name: 'master'  }
#{ name: 'master', 'ip: v4prefix + "11"' },
  #{ name: 'master', 'ip: v6prefix + "11"' },
  #{ name: 'slave', 'ip: v4prefix + "12"' },
  #{ name: 'slave', 'ip: v6prefix + "12"' },
    #{ name: 'slave' , ip: '172.28.128.12',ip6: 'fde4:8dba:82e1::c4' }
#  { name: 'slave' , ip: '172.28.128.12' }
]
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'bertvv/centos72'

  hosts.each do |host|
    host_name = BASE_NAME + host[:name]

    config.vm.define host_name do |node|

#node.vm.network 'private_network', type: "dhcp"
#config.vm.network "private_network", ip: "10.0.0.100", :name => 'vboxnet3'
      node.vm.network 'private_network', ip: "172.28.128.100", :mac => "080027beb5a1"
      #node.vm.network "private_network", ip: "172.28.128.100"
#config.vm.network "private_network", ip: "10.0.0.2", :name => 'vboxnet3'

      #node.vm.network "public_network", bridge: "enp0s20u2u1u4", use_dhcp_assigned_default_route: true
  #    node.vm.network 'private_network', ip: host[:ip]
    #  node.vm.network "private_network", ip: host[:ip6]
      node.vm.provision 'ansible' do |ansible|
        ansible.playbook = "../../../../playbook/dhcpmaster.yml"
      node.vm.provision "shell",
        run: "always",
        inline: "ip -6 addr add 2001::db8:0:1:128/64 dev enp0s8 "
        #ansible.playbook = 'test.yml'         # Elaborate test that shows all features
        # ansible.playbook = 'test-bare.yml'  # Minimal test case
      end
    end
  end
end





  #config.vm.box = "centos/7"








  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
