#- name: Install Name Server with Chroot
#  yum: name=bind-chroot state=latest update_cache=yes
#  become: True
#  become_user: root
#  tags: bind-chroot
#  when: dns_chroot_enabled == True
- name: Install bind-chroot and bind-utils package
  yum: name="{{item}}" state=present
  become: True
  become_user: root
  with_items:
    - bind-chroot
    - bind-utils
  tags: bind
  when: dns_chroot_enabled == True
