#- name: Install Name Server
#  yum: name=bind state=latest update_cache=yes
#  become: True
#  become_user: root
#  tags: bind
# when: dns_enabled == True
- name: Install bind and bind-utils package
  yum: name="{{item}}" state=present
  become: True
  become_user: root
  with_items:
    - bind
    - bind-utils
  tags: bind
  when: dns_enabled == True
