---
- include: "roles/dns/tasks/base-{{package_manager}}-bind.yml"
  when: dns_enabled == True
- include: "roles/dns/tasks/base-{{package_manager}}-bind-chroot.yml"
  when: dns_chroot_enabled == True

- name: debug
  debug: msg={{ item }}
  with_items: "{{ zone_names }}"

- name: Copy zone forward files for all zones to /var/named
  become: True
  become_user: root
  template: src="zone.forward.j2" dest="/var/named/{{item}}forward" owner=root group=named mode=640
  with_items:
    - "{{ zone_names }}"
  notify:
    - restart bind
  when: dns_enabled == True
  #when:  {% if dns_enabled == True && forward_zones_reg == True %} True {% else %} False {% endif %}
  #when: dns_enabled == True && forward_zones_reg == True

- name: Copy zone forward files for all zones to /var/named with dns-chroot
  become: True
  become_user: root
  template: src="zone.forward.j2" dest="/var/named/{{item}}forward" owner=root group=named mode=640
  with_items: zone_names
  notify:
    - restart bind-chroot
  when: dns_chroot_enabled == True
  #when: {% if dns_chroot_enabled == True && forward_zones_reg == True %} True {% else %} False {% endif %}
  #when: dns_chroot_enabled == True && forward_zones_reg == True

- name: Create custom named.conf with desired zone with chroot
  become: True
  become_user: root
  template: src=named.conf.j2 dest=/etc/named.conf owner=root group=named mode=640
  notify:
    - restart bind-chroot
  when: dns_chroot_enabled == True

- name: Create custom named.conf with desired zone
  become: True
  become_user: root
  template: src=named.conf.j2 dest=/etc/named.conf owner=root group=named mode=640
  notify:
    - restart bind
  when: dns_enabled == True


- name: Disable IPv6 support dns
  become: True
  become_user: root
  lineinfile: dest=/etc/sysconfig/named line='OPTIONS="-4"' regexp="^OPTIONS"
  notify:
    - restart bind
  when: dns_enabled == True

- name: Disable IPv6 support
  become: True
  become_user: root
  lineinfile: dest=/etc/sysconfig/named line='OPTIONS="-4"' regexp="^OPTIONS"
  notify:
    - restart bind-chroot
  when: dns_chroot_enabled == True

- name: Start and enable bind service
  become: True
  become_user: root
  service: name=named state=started enabled=yes
  when: dns_enabled == True

- name: Start and enable bind service dnschroot
  become: True
  become_user: root
  service: name=named state=started enabled=yes
  when: dns_chroot_enabled == True
