---
- name: restart bind-chroot
  service: name=named state=restarted
  become: True
  become_user: root
  tags: bind-chroot
  when: dns_chroot_enabled ==  True
- name: restart bind
  service: name=named state=restarted
  become: True
  become_user: root
  tags: bind
  when: dns_enabled ==  True
