require 'rbconfig'
Vagrant.configure("2") do |config|
  H = 1

  VAGRANT_VM_PROVIDER = "virtualbox"
  ANSIBLE_RAW_SSH_ARGS = []

  (1..H-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS < "-o IdentityFile=.vagrant/machines/routerINT#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..H).each do |machine_id|
    config.vm.define "routerINT#{machine_id}" do |machine|
      machine.vm.box = "centos/7"
      machine.vm.hostname = "routerINT#{machine_id}"
      machine.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.2.66", auto_config: false
      machine.vm.network "private_network", ip: "172.16.1.19", auto_config: false


      #Stop NetworkManager
      config.vm.provision "shell",
      run:"always",
      inline:"echo 'systemctl stop NetworkManager'; systemctl stop NetworkManager"

      # manual ip bridge eth1
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip bridge eth1 192.168.2.66';ip address flush dev eth1; ip address add 192.168.2.66/24 dev eth1;ip link set dev eth1 up"

      # manual ip private eth2
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip private eth2 172.16.1.19';ip address flush dev eth2 ;ip address add 172.16.1.19/16 dev eth2;ip link set dev eth2 up"

      #forwarding
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'enableing ip forwarding';echo 1 > /proc/sys/net/ipv4/ip_forward"

      #install net-tools
      config.vm.provision "shell",
      run: "always",
      inline: "yum install net-tools -y"

      # delete default gw on eth0
      config.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"


      # default router
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for bridge interface';ip route add default via 192.168.2.1 dev eth1"
      #inline: "ip route add default via 192.168.2.1 dev eth1"

      # static router eth2
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring network gw for 172.16.0.0';ip route add 172.16.1.0 via 172.16.1.2 dev eth2"
      #inline: "route add -net 172.16.0.0 netmask 255.255.255.0 gw 172.16.1.1"

      #masquerading
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading'; iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE"

      #masquerading
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading'; iptables -A FORWARD -i eth1 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT"


      #masquerading
      config.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading';  iptables -A FORWARD -i eth2 -o eth1 -j ACCEPT"



    end
  end
end

