require 'rbconfig'
Vagrant.configure("2") do |config1|
  R = 1

  VAGRANT_VM_PROVIDER = "virtualbox"
  ANSIBLE_RAW_SSH_ARGS = []

  (1..R-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS < "-o IdentityFile=.vagrant/machines/routerPRIV#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..R).each do |machine_id|
    config1.vm.define "routerPRIV#{machine_id}" do |machine1|
      #config.vm.network "public_network", bridge: "en0", use_dhcp_assigned_default_route: true
      machine1.vm.box = "centos/7"
      machine1.vm.hostname = "routerPRIV#{machine_id}"
      machine1.vm.network "private_network", ip: "10.1.1.2", auto_config: false
      machine1.vm.network "private_network", ip: "172.16.1.2", auto_config: false


      #Stop NetworkManager
      config1.vm.provision "shell",
      run:"always",
      inline:"echo 'systemctl stop NetworkManager'; systemctl stop NetworkManager"

      # manual ip private eth1
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip private eth1 10.1.1.2'; ip address flush dev eth1;ip address add 10.1.1.2/8 dev eth1;ip link set dev eth1 up"

      # manual ip private eth2
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip private eth2 172.16.1.2';ip address flush dev eth2;ip address add 172.16.1.2/16 dev eth2;ip link set dev eth2 up"

      #forwarding
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'enableing ip forwarding';echo 1 > /proc/sys/net/ipv4/ip_forward"

      #install net-tools
      config1.vm.provision "shell",
      run: "always",
      inline: "yum install -y net-tools "

      # delete default gw on eth0
      config1.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"


      # static router eth2
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for private interface 172.16.0.0';ip route add 172.16.1.0 via 172.16.1.2 dev eth2"
      #inline: "route add -net 172.16.0.0 netmask 255.255.255.0 gw 172.16.1.1"

      # static router eth2
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for private interface 172.16.0.0';ip route add 10.1.1.0 via 10.1.1.2 dev eth1"
      #inline: "route add -net 172.16.0.0 netmask 255.255.255.0 gw 172.16.1.1"

      # default router
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for private interface 10.0.0.0';ip route add default via 172.16.1.19 dev eth2"
      #inline: "ip route add default via 192.168.2.1 dev eth1"

      #masquerading
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading'; iptables -t nat -A POSTROUTING -o eth2 -j MASQUERADE"

      #masquerading
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading'; iptables -A FORWARD -i eth2 -o eth1 -m state --state RELATED,ESTABLISHED -j ACCEPT"


      #masquerading
      config1.vm.provision "shell",
      run: "always",
      inline: "echo 'masquerading'; iptables -A FORWARD -i eth1 -o eth2 -j ACCEPT"


    end
  end
end
