- name: Install packages
  become: True
  with_items: package_list
  action: "{{ ansible_pkg_mgr }} state=installed name={{ mysql_name}}"

- name: Ensure MySQL Python libraries are installed.
  become: True
  with_items: package_list
  action: "{{ ansible_pkg_mgr }} name={{ mysql_python }} state=installed "

- name: Ensure MySQL is started and enabled on boot.
  become: True
  service: "name={{ mysql_name }} state=started enabled=yes"
