# Has to be after the root password assignment, for idempotency.
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false

- name: Copy .my.cnf file with root password credentials.
  become: True
  template:
    src: "root-my.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600





# Set root password for MySQL < 5.7.x.
- name: Update MySQL root password for localhost root account (< 5.7.x).
  become: True
  shell: >
    mysql -NBe
    'SET PASSWORD FOR "{{ mysql_root_username }}"@"localhost" = PASSWORD("{{ mysql_root_password }}");'
  when: (mysql_name ) and ('5.7.' not in mysql_cli_version.stdout)

- name: Remove ssh.cfg config
  file: path="{{ mysql_root_home }}/.my.cnf" state=absent

- name: Copy .my.cnf file with root password credentials.
  become: True
  template:
    src: "root-my-new.cnf.j2"
    dest: "{{ mysql_root_home }}/.my.cnf"
    owner: root
    group: root
    mode: 0600
