- include: "roles/base/tasks/base-{{package_manager}}.yml"
#- include: "base-{{package_manager}}.yml"

- name: Passwordless sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
  when: "{{passwordless_sudo}}"
  become: True
  become_user: root
