require 'rbconfig'
Vagrant.configure("2") do |config3|
  J = 1

  VAGRANT_VM_PROVIDER = "virtualbox"
  ANSIBLE_RAW_SSH_ARGS = []

  (1..J-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS < "-o IdentityFile=.vagrant/machines/hostB#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..J).each do |machine_id|
    config3.vm.define "hostB#{machine_id}" do |machine3|
      #config.vm.network "public_network", bridge: "en0", use_dhcp_assigned_default_route: true
      machine3.vm.box = "debian/stretch64"
      machine3.vm.hostname = "hostB#{machine_id}"
      machine3.vm.network "private_network", ip: "172.16.1.20", auto_config: false

      # manual ip private eth1
      config3.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring ip private eth1 172.16.1.20';ip address flush dev eth1;ip address add 172.16.1.20/16 dev eth1; ip link set dev eth1 up"

      #forwarding
      config3.vm.provision "shell",
      run: "always",
      inline: "echo 'enableing ip forwarding';echo 1 > /proc/sys/net/ipv4/ip_forward"

      #install net-tools
      config3.vm.provision "shell",
      run: "always",
      inline: "apt-get install net-tools --assume-yes"

      # delete default gw on eth0
      config3.vm.provision "shell",
      run: "always",
      inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"

      # static router eth2
      config3.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring network gw for 172.16.0.0';ip route add 172.16.1.0 via 172.16.1.2 dev eth1"
      #inline: "route add -net 172.16.0.0 netmask 255.255.255.0 gw 172.16.1.1"

      # default router
      config3.vm.provision "shell",
      run: "always",
      inline: "echo 'Configuring default gw for bridge interface';ip route add default via 172.16.1.2"
      #inline: "ip route add default via 192.168.2.1 dev eth1"



    end
  end
end
